<html><head></head><body><a href="http://caucasusoffline.com" class="btn btn-rised btn-default btn-geo" target="_blank" style="display:block"><i class="icon icon-material-launch"></i>&nbsp;&nbsp;ამონაწერი</a>



<div class="panel panel-default">
	 
	<div class="panel-body">
		<div class="table-responsive">
			<table class="mun-info table table-striped">
				<tbody>
			
				
				<tr>
					<td class="col-sm-3">დასახელება</td>
					<td class="col-sm-8"><br><strong>ახალგორის მუნიციპალიტეტი</strong></td>
				</tr>
			
			</tbody></table>
		</div>
	</div>
</div><div class="panel panel-default">
	<div class="panel-heading">დასახლებათა დასახელება  (68)</div>
	<div class="panel-body">
<div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ალევი</div>
</div><div class="settlement settlement-2">
<div class="category">დაბა</div>
<div class="name">ახალგორი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ახალდაბა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ახმაჯი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ბაზუაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ბალაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ბეჟანტყევი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">გავაზი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">გარუბანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">გდუ</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">გეზევრეთი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">გრუ</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">გუდაწვერი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">დადიანეთი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">დელკანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">დორეთკარი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ელოიაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ერედა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ვაშლოვანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ზაყორი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ზემო ბოლი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ზოდეხი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">თინიკაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">თოხთა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">იკოთი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">კარელთკაარი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">კორინთა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ლარგვისი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ლოთიაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მარტაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მახიარეთი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მიდელაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მონასტერი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მორბედაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მოსაბრუნი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მოჭალიეთი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მსხლები</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მუჯუხი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">მშველიეთი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ნაგომევი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ნაცარა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ნახიდი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ორჭოსანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">პავლიაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">სალბიერი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">საძეგური</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">უკანამხარე</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">უკანუბანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ქენქაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ქვემო ბოლი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ქურთა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ყანჩავეთი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ყველდაბა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ყოჩიაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">შიუკაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ჩანდარი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ჩიტიაანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ცხავატი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ცხილონი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ძეგლევი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ძუკათკაუ</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">წინაგარი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">წიპტაურიანი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">წირი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">წირქოლი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">წოლდა</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ჭორჭოხი</div>
</div><div class="settlement settlement-1">
<div class="category">სოფელი</div>
<div class="name">ხარბალი</div>
</div>	</div>
</div></body></html>